spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled: true
      file-size-threshold: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qkj_project?useUnicode = true&characterEncoding = utf8&useSSL = false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: Admin@123
    virtual-host: /study

logging:
  level:
    com.qkj.project: INFO # 返回日志级别

# 路径拦截
auth:
  # 不需要 token 校验的接口
  ignoreUrls: '/qkj/login,/qkj/file/file_content,/qkj/file/url,/qkj/file'
  # token 以参数的方式传递到后端的接口 eg: 文件上传、文件下载
  queryUrls: ''
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI71DbL/2sMTAmP22jdlhhU9TiVHjWr3I/kDTX821puYX5Q6nkb9bcTi3KjIMczTbSw4Lnem0flidzBtene+ltUCAwEAAQ==
  private-key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAjvUNsv/awxMCY/baN2WGFT1OJUeNavcj+QNNfzbWm5hflDqeRv1txOLcqMgxzNNtLDgud6bR+WJ3MG16d76W1QIDAQABAkBbXwWCg0WvqVa9zelrvtgUezqXWURqOcwkPJgr10ET8Ttp3ivS0eVQJKsiw2L44tpik3dRexas5JvJXeG63XgBAiEAxu/cvaBQmiG1M+FO/Nn4fZSuCJRkLvD27azvVLeIdOUCIQC39ouCFlvovxVwBMsdgM2E+T1TnuTozWMTG+E7surrMQIgVipab//aKYhkFd6G+dnnWW1mm+y6H+La8UMwPn9oKUkCIHLFLx5Wwrp/VGmRpALhE9dtA9TCof+X+8K1Nxzer+9RAiBPXK5Qeqa64m0qBGdl+P+FETWVqm6hxez9Fxp/iLo+Jw==
  type: jwt # 现有 1-jwt:通过 jwt 生成 token, 2-redis: 通过 redis 存储 token
  login-expire-time: 3600 # redis 过期时间 8小时

# minio 存储地址
unify:
#  minio:
#    endpoint: http://127.0.0.1:9000
#    accessKey: admin
#    secretKey: Admin@123
#    bucketName: personal-bucket
#    zipBucketName: zip-bucket
#  minio:
#    endpoint: http://192.168.51.156:9001
#    accessKey: minioadmin
#    secretKey: Admin@123
#    bucketName: test-bucket
#    zipBucketName: test-bucket
  minio:
    endpoint: http://13.11.102.254:6188  # 附件存储
    accessKey: yIi2K47J0Blpgz7xLQE0
    secretKey: MPGGpvUVIwhDvwqmbD7HV70pxUS2YY4SgVcCLwvw
    bucketName: sharex-dev

# 异步任务线程池配置
task:
  pool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 50